### ISSUE TITLE
Logic: Advance Time

### ISSUE THREAD

**Issue by SethPattee** [SethPattee/SAD-Final-Project#96]
Check giver supplier relationship after advance time so that we don't add products that are not in the supplier don't make it to the receiver.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the AdvanceTime method in SupplyChainViewModel to check if the supplier has the product before shipping it to the receiver. This ensures that products not present in the supplier's inventory don't make it to the receiver.

You can review changes in this commit: https://github.com/lkilu6456546/SethPattee-SAD-Final-Project-96/commit/5934ae99339757b2940b94d95c6de3e67b04229b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
